# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doorac', '0002_auto_20180507_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(default='', max_length=30)),
                ('name', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('approveTag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TmpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
