# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorac', '0003_devices_tmpdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='approveTag',
            new_name='approve_tag',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='deviceID',
        ),
        migrations.RemoveField(
            model_name='log',
            name='text',
        ),
        migrations.AddField(
            model_name='devices',
            name='dev_id',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='door',
            name='door_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='log',
            name='detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='log_event',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='rfid_uid',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tmpdata',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
