# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('doorac', '0005_auto_20180515_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='room',
            name='detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
