# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doorac', '0006_auto_20180515_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doorac.Room'),
        ),
    ]
